---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prefect-agent
  name: prefect-agent
  namespace: ${BAKERY_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
      - name: agent
        image: ${AZURE_BAKERY_IMAGE}
        imagePullPolicy: Always
        volumeMounts:
        - name: job-template
          mountPath: "/job-template"
          readOnly: true
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 40
        command:
          - /bin/bash
          - -c
        args:
          - "prefect agent kubernetes start --job-template=/job-template/job_template.yaml"
        env:
          - name: PREFECT__CLOUD__AGENT__AUTH_TOKEN
            value: ${PREFECT__CLOUD__AGENT__AUTH_TOKEN}
          - name: PREFECT__CLOUD__API
            value: https://api.prefect.io
          - name: NAMESPACE
            value: ${BAKERY_NAMESPACE}
          - name: IMAGE_PULL_SECRETS
            value: ''
          - name: PREFECT__CLOUD__AGENT__LABELS
            value: '${PREFECT__CLOUD__AGENT__LABELS}'
          - name: JOB_MEM_REQUEST
            value: ''
          - name: JOB_MEM_LIMIT
            value: ''
          - name: JOB_CPU_REQUEST
            value: ''
          - name: JOB_CPU_LIMIT
            value: ''
          - name: IMAGE_PULL_POLICY
            value: ''
          - name: SERVICE_ACCOUNT_NAME
            value: 'default'
          - name: PREFECT__BACKEND
            value: cloud
          - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
            value: http://:8080
          - name: DELETE_FINISHED_JOBS
            value: 'False'
      volumes:
      - name: job-template
        configMap:
          name: job-template
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-agent-rbac
  namespace: ${BAKERY_NAMESPACE}
rules:
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - events
  - pods
  - pods/log
  - services
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prefect-agent-rbac
  namespace: ${BAKERY_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-agent-rbac
subjects:
- kind: ServiceAccount
  name: default

