name: terraform-lint

on: [push, pull_request]

jobs:
  terraform-lint:
    name: Terraform Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main